title: Yash Chaurasia
markdown: kramdown

# for atom feed
author:
  name: Yash Chaurasia
  email: yash.chaurasia@research.iiit.ac.in

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true
  entries:
    output: true

defaults:
  - scope:
      path: "_entries"
      type: "entries"
    values:
      layout: "entry"
      permalink: /entries/:title/
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
# keep_files: ["yash_image.jpg"]
